trigger: none

pool: skp-pool-nov

stages:
  - stage: Install
    displayName: TF Install
    jobs:
      - job: Installation
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
  - stage: Init_Validate_Fmt
    jobs:
      - job: 
        steps:
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            backendServiceArm: 'first_sc_nov'
            backendAzureRmStorageAccountName: 'skpstoragebackend'
            backendAzureRmContainerName: 'skp-container'
            backendAzureRmKey: 'saurabhtf.tfstate'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'first_sc_nov'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            environmentServiceNameAzureRM: 'first_sc_nov'

  # - stage: Terraform_scan
  #   jobs:
  #     - job: Terraform_scan
  #       steps:
  #       - task: tfsec@1
  #         inputs:
  #           version: 'v1.26.0'
  
  # - stage: Terraform_Plan
        

