trigger: none

pool: skp-pool-nov

stages:
  - stage: Install_Init_Validate_Fmt
    displayName: Install_Init_Validate_Fmt
    jobs:
      - job: TF_Installation
        displayName: Terraform Install
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            backendServiceArm: 'first_sc_nov'
            backendAzureRmStorageAccountName: 'skpstoragebackend'
            backendAzureRmContainerName: 'skp-container'
            backendAzureRmKey: 'saurabhtf.tfstate'
        - task: TerraformTask@5
          displayName: Terraform Validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
        - task: TerraformTask@5
          displayName: Terraform Fmt
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'first_sc_nov'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            environmentServiceNameAzureRM: 'first_sc_nov'

  - stage: Approval_stage
    displayName: Approval stage
    dependsOn: Install_Init_Validate_Fmt
    pool: Server
    jobs:
      - job: 
        displayName: Manual Validation
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'saurabhpatel320@gmail.com'

  - stage: Apply_stage
    displayName: Apply
    dependsOn: Approval_stage
    jobs:
      - job: 
        displayName: Apply
        steps:
        # - task: TerraformTask@5
        #   displayName: Init 2
        #   inputs:
        #     provider: 'azurerm'
        #     command: 'init'
        #     workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
        #     backendServiceArm: 'first_sc_nov'
        #     backendAzureRmStorageAccountName: 'skpstoragebackend'
        #     backendAzureRmContainerName: 'skp-container'
        #     backendAzureRmKey: 'saurabhtf.tfstate'
        - task: TerraformTask@5
          displayName: Terraform Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
            environmentServiceNameAzureRM: 'first_sc_nov'

  - stage: Destroy_stage
    dependsOn: Apply_stage
    displayName: Destroy
    jobs:
    - job: Destroy
      displayName: Destroy 
      steps:
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'destroy'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
          environmentServiceNameAzureRM: 'first_sc_nov'
      