trigger: none

pool: skp_pool_dec

parameters:
- name: env
  displayName: environment
  type: string
  values: 
  - dev
  - prod

stages:
  - stage: Install_Init_Validate_Fmt
    displayName: Install_Init_Validate_Fmt
    jobs:
      - job: TF_Installation
        displayName: Terraform Install
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: Terraform Init
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.env }}'
            backendServiceArm: 'dec_sc1'
            backendAzureRmStorageAccountName: 'skpstoragebackend1'
            backendAzureRmContainerName: 'skp-container'
            backendAzureRmKey: '${{ parameters.env }}.tfstate'
        - task: TerraformTask@5
          displayName: Terraform Validate
          inputs:
            provider: 'azurerm'
            command: 'validate'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.env }}'
        - task: TerraformTask@5
          displayName: Terraform Fmt
          inputs:
            provider: 'azurerm'
            command: 'custom'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.env }}'
            outputTo: 'console'
            customCommand: 'fmt'
            environmentServiceNameAzureRM: 'dec_sc1'
        - task: TerraformTask@5
          inputs:
            provider: 'azurerm'
            command: 'plan'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.env }}'
            environmentServiceNameAzureRM: 'dec_sc1'

  - stage: Approval_stage
    displayName: Approval stage
    dependsOn: Install_Init_Validate_Fmt
    pool: Server
    jobs:
      - job: 
        displayName: Manual Validation
        steps:
        - task: ManualValidation@1
          inputs:
            notifyUsers: 'saurabhpatel320@gmail.com'

  - stage: Apply_stage
    displayName: Apply
    dependsOn: Approval_stage
    jobs:
      - job: 
        displayName: Apply
        steps:
        - task: TerraformInstaller@1
          inputs:
            terraformVersion: 'latest'
        - task: TerraformTask@5
          displayName: Init 2
          inputs:
            provider: 'azurerm'
            command: 'init'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.env }}'
            backendServiceArm: 'dec_sc1'
            backendAzureRmStorageAccountName: 'skpstoragebackend1'
            backendAzureRmContainerName: 'skp-container'
            backendAzureRmKey: '${{ parameters.env }}.tfstate'
        - task: TerraformTask@5
          displayName: Terraform Apply
          inputs:
            provider: 'azurerm'
            command: 'apply'
            workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.env }}'
            environmentServiceNameAzureRM: 'dec_sc1'

  - stage: Destroy_stage
    dependsOn: Apply_stage
    displayName: Destroy
    jobs:
    - job: Destroy
      displayName: Destroy 
      steps:
      - task: TerraformInstaller@1
        inputs:
          terraformVersion: 'latest'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.env }}'
          backendServiceArm: 'dec_sc1'
          backendAzureRmStorageAccountName: 'skpstoragebackend1'
          backendAzureRmContainerName: 'skp-container'
          backendAzureRmKey: '${{ parameters.env }}.tfstate'
      - task: TerraformTask@5
        inputs:
          provider: 'azurerm'
          command: 'destroy'
          workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/${{ parameters.env }}'
          environmentServiceNameAzureRM: 'dec_sc1'
      