trigger: none

pool: skp-pool-nov

jobs:
  - job: Terraform_init
    displayName: Init
    steps:
    - task: TerraformInstaller@1
      displayName: Install Terraform
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      displayName: Terraform Init
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/Environment/Dev'
        backendServiceArm: 'first_sc_nov'
        backendAzureRmStorageAccountName: 'skpstoragebackend'
        backendAzureRmContainerName: 'skp-container'
        backendAzureRmKey: 'saurabhtf.tfstate'
    - task: TerraformTask@5
      displayName: Terraform Validate
      inputs:
        provider: 'azurerm'
        command: 'validate'
    - task: TerraformTask@5
      displayName: Terraform fmt
      inputs:
        provider: 'azurerm'
        command: 'custom'
        commandOptions: 'fmt'
        outputTo: 'console'
        environmentServiceNameAzureRM: 'first_sc_nov'
    - task: TerraformTask@5
      displayName: Terraform Plan
      inputs:
        provider: 'azurerm'
        command: 'plan'
        environmentServiceNameAzureRM: 'first_sc_nov'